import type { Metadata } from "next";

import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/*import { useEffect, useState } from "react";

function useIsDark() {
  const [isDark, setIsDark] = useState(
    window.matchMedia('(prefers-color-scheme: dark)').matches
  )

  function handler(ele: MediaQueryListEvent) {
    setIsDark(ele.matches)
  }

  useEffect(() => {
    const mediaQuery = window.matchMedia('(prefers-color-scheme: dark)')
    
    mediaQuery.addEventListener('change', handler)

    return () => mediaQuery.removeEventListener('change', handler)
  })
  
  return isDark
}*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          
        </header>
        <nav>
          <ul>
            <li><Link href="/">Home</Link></li>
            <li><Link href="/help">Help</Link></li>
          </ul>
        </nav>
        <hr />
        <main>
          {children}
        </main>
        <hr />
        <footer>
          Powered by Next on Vercel
        </footer>
      </body>
    </html>
  );
}
