import type { Metadata } from "next";

import "./globals.css";
import Link from "next/link";
import { createClient } from "@/utils/supabase/server";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/*import { useEffect, useState } from "react";

function useIsDark() {
  const [isDark, setIsDark] = useState(
    window.matchMedia('(prefers-color-scheme: dark)').matches
  )

  function handler(ele: MediaQueryListEvent) {
    setIsDark(ele.matches)
  }

  useEffect(() => {
    const mediaQuery = window.matchMedia('(prefers-color-scheme: dark)')
    
    mediaQuery.addEventListener('change', handler)

    return () => mediaQuery.removeEventListener('change', handler)
  })
  
  return isDark
}*/

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = createClient(await cookies())

  const { data } = await supabase.auth.getUser()
  const user = data.user

  return (
    <html lang="en">
      <body>
        <header>
          
        </header>
        <nav>
          <ul>
            <li><Link href="/">Home</Link></li>
            {user
              ? <li>Logout</li>
              : <li><Link href="/account/login">Login</Link></li>
            }
          </ul>
        </nav>
        { user ? <p>Hi {user.email}</p> : null}
        <hr />
        <main>
          {children}
        </main>
        <hr />
        <footer>
          Powered by Next on Vercel
        </footer>
      </body>
    </html>
  );
}
